#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


source ../postproc_common
ret=0

#testByte2
#testShort2

METHODS="testInt1
testInt2
testInt3
testByte1
testByte3
testShort1
testShort3
testLong1
testLong2
testLong3
testFloat1
testFloat2
testDouble1
testDouble2"

for method in $METHODS
do
    search_method $method
    if [[ $? -ne 0 ]]
    then
        echo "Couldn't find test $method in the list of optimized loops"
        ret=1
    fi
done
exit $ret
