#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


source ../postproc_common
ret=0

METHODS="testInt1
testInt2
testInt3
testInt5
testInt6
testInt7
testByte1
testByte2
testByte3
testByte5
testByte6
testByte7
testShort1
testShort2
testShort3
testShort5
testShort6
testShort7
testLong1
testLong2
testLong3
testLong5
testLong6
testLong7
"

for method in $METHODS
do
    search_method $method
    if [[ $? -ne 0 ]]
    then
        echo "Couldn't find test $method in the list of optimized loops"
        ret=1
    fi
done
exit $ret
