#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


packagedir=`echo "$(cd $(dirname $0); pwd)/../"`

declare -a testMethodsCounts=('testLoopAddLess:1' 'testLoopAddGreater:0' 'testLoopAddInfinity:1' 'testLoopSubLess:1' 'testLoopSubGreater:0' 'testLoopSubInfinity:1'  'testLoopMulLess:1' 'testLoopMulGreater:0' 'testLoopMulInfinity:1'  'testLoopMulZero:1' 'testLoopDivLess:1' 'testLoopDivGreater:0' 'testLoopDivZero:1' 'testLoopDivInfinity:1' 'testLoopRemLess:1' 'testLoopRemGreater:1' 'testLoopRemZero:1' 'testLoopNaN:0' 'testLoopInfinity1:1' 'testLoopInfinity2:1' 'testLoopUnkownStart:0')

# include the package's postproc
if [ -f $packagedir/postproc_common ]; then
    source $packagedir/postproc_common
fi

