#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


commontestdir=`echo "$(cd $(dirname $0); pwd)/../"`
field=InstanceField
tocheck=sunk
message="There are 1 get/set pairs and 1 sets to sink out of the loop"
testtype=positive

# include the package's postproc
if [ -f $commontestdir/postproc_common ]; then
    source $commontestdir/postproc_common
fi

