#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


packagedir=`echo "$(cd $(dirname $0); pwd)/../"`

declare -a testMethodsCounts=('testLoopAddInt:1' 'testLoopSubInt:2' 'testLoopSubLong:4' 'testLoopSubLongModifiedInOuterLoop:3' 'testLoopSubLongReadInOuterLoopAndNonConstBound:3'  'testLoopMulIntNested:1' 'testLoopMulLongNested:0' 'testLoopDivNested1:4' 'testLoopRemIntNested:3' 'testLoopAddLongSeveralLoops:3' 'testLoopDivNested2:1' 'testLoopDivNested3:4' 'testLoopDivNested4:0')

# include the package's postproc
if [ -f $packagedir/postproc_common ]; then
    source $packagedir/postproc_common
fi

