#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


packagedir=`echo "$(cd $(dirname $0); pwd)/../"`

#declare -a testMethodsCounts=('testLoop1MulInt:1' 'testLoopNeg1MulInt:1' 'testLoopZeroMulInt:1' 'testLoop1MulLong:1' 'testLoopNeg1MulLong:1' 'testLoopOverflowMulLong:0' 'testLoopOverflowMulInt:0' 'testLoopZeroMulLong:1' 'testLoopOverflowToZeroNegMulInt:1' 'testLoopOverflowToZeroPosMulInt:1' 'testLoopOverflowToZeroNegMulLong:1' 'testLoopOverflowToZeroPosMulLong:1' 'testLoopOverflowMaxMulInt:0' 'testLoopOverflowMinMulInt:0' 'testLoopOverflowMaxMulLong:0' 'testLoopOverflowMinMulLong:0' 'testLoopOverflowMin1MulInt:1'  'testLoopOverflowMin1MulLong:1')
declare -a testMethodsCounts=('testLoopOverflowMulLong:0' 'testLoopOverflowMulInt:0' 'testLoopOverflowToZeroNegMulInt:1' 'testLoopOverflowToZeroPosMulInt:1' 'testLoopOverflowToZeroNegMulLong:1' 'testLoopOverflowToZeroPosMulLong:1' 'testLoopOverflowMaxMulInt:0' 'testLoopOverflowMinMulInt:0' 'testLoopOverflowMaxMulLong:0' 'testLoopOverflowMinMulLong:0' 'testLoopOverflowMin1MulInt:1'  'testLoopOverflowMin1MulLong:1')

# include the package's postproc
if [ -f $packagedir/postproc_common ]; then
    source $packagedir/postproc_common
fi

