#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


packagedir=`echo "$(cd $(dirname $0); pwd)/../"`

success_message="Successfully peeled loop with header block"

declare -a testMethodsCounts=("test_01:$success_message==1" "test_02:$success_message==1" "test_03:$success_message==1" "test_04:$success_message==1" "test_05:$success_message==1" "test_06:$success_message==1" "test_07:$success_message==2" "test_08:$success_message==1"  "test_09:$success_message==0")

# include the package's postproc
if [ -f $packagedir/postproc_common ]; then
    source $packagedir/postproc_common
fi

