#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

logcat=$1

function Exit()
{
   echo $2
   exit $1
}

# example:
# I dex2oat : loop_full_unrolling: Loop #3 of method int OptimizationTests.LoopUnrolling.RangeCheckSetter.Main.testLoop() has been successfully fully unrolled by factor 9

    cat ${logcat} | grep -E "loop_full_unrolling: Loop #[0-9]+ of method [int|long|boolean|char]+ OptimizationTests.${pckgname}.${testname}.Main.testLoop(.*) has been successfully fully unrolled by factor [0-9]+"
    if [ "$?" != "0" ]; then
        echo `cat ${logcat} | grep -E "OptimizationTests.${pckgname}.${testname}.Main.testLoop(.*)"`
        Exit 1 "FAILED: loop of the method OptimizationTests.${pckgname}.${testname}.Main.testLoop(.*) has not been unrolled"
    fi
    Exit 0 "PASSED: Loop has been successfully fully unrolled"
