#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


packagedir=`echo "$(cd $(dirname $0); pwd)/../"`
currdir=`echo "$(cd $(dirname $0); pwd)"`
declare -a testMethodsCounts=('testLoopAddInt:1' 'testLoopAddLong:1' 'testLoopSubInt:1' 'testLoopSubLong:1' 'testLoopMulInt:1' 'testLoopMulLong:1' 'testLoopDivInt:1' 'testLoopDivLong:1' 'testLoopRemInt:1' 'testLoopRemLong:1')
declare -a testMethodsCountsNTM=('testLoopAddInt:1' 'testLoopAddLong:1' 'testLoopSubInt:1' 'testLoopSubLong:1' 'testLoopMulInt:1' 'testLoopMulLong:1' 'testLoopDivInt:1' 'testLoopDivLong:1' 'testLoopRemInt:1' 'testLoopRemLong:1')


logcat=$1
str_res=""
res=0

packagename=$(basename `cd $packagedir ; pwd`)
metapackagename=$(dirname `cd $packagedir ; pwd`)
testname=${PWD##*/}
packagename=${PWD%%/$testname}
packagename=${packagename##*/}
metapackagename=${PWD%%/$packagename/$testname}
metapackagename=${metapackagename##*/}

function Exit()
{

   if [ ! $1 = 0 ]; then
       echo -e "FAILED:\n"$2
   else 
       echo -e "PASSED:\n"$2
   fi

   exit $1
}


#TODO: remove this function if unused
function FilterLogcat() 
{
    #Remove everything except dex2oat from logcat.
    cat ${logcat} | grep "dex2oat" > ${logcat}_filtered
    if [ ! -s ${logcat}_filtered ] ; then
        Exit 1 "Failed to process logcat file $logcat: expected dex2oat entries not found"
    else 
        logcat=${logcat}_filtered
    fi
}

function ExtractMethodLogcat() {
    methodName=$1
    patternBegin=$2
    suffix=$3
    number_regexp='^[0-9]+$'
#    pattern="constant_calculation_sinking: Try to optimize loop in method .* ${metapackagename}.${packagename}.${testname}.Main"
    pattern="$patternBegin .* ${metapackagename}.${packagename}.${testname}.Main"

    linenumber1=`grep -n -E "${pattern}\.${methodName}\(" ${logcat} | cut -f1 -d: | head  -1`

    if ! [[ $linenumber1 =~ $number_regexp ]] ; then
#echo "UNEXPECTED: Constant Calculation Sinking messages not found, check if optimization is not disabled"
        return
    fi



    linenumber2=`tail -n +$((linenumber1+1)) $logcat |grep -n -E "${pattern}"  | grep -v -E "${methodName}" | cut -f1 -d: | head  -1`

    flag_no_other_methods="false"
    if [[ "x$linenumber2" == "x" ]]; then
        linenumber2=`cat ${logcat} | wc -l`
        flag_no_other_methods="true"
    else 
# remember that we cut linenumber 1 lines when calculating linenumber2
        linenumber2=$((linenumber2+linenumber1))
    fi


    if ! [[ $linenumber2 =~ $number_regexp ]] ; then
        return
    fi

    if [[ $flag_no_other_method =~ "true" ]] ; then 
       linenumber2=$((linenumber2-1))
    fi
    

    sed -n ${linenumber1},${linenumber2}p  ${logcat} > ${logcat}_${methodName}_${suffix}
    if [ ! -s ${logcat}_${methodName}_${suffix} ] ; then
       echo "UNEXPECTED: Failed to extract $patternBegin messages for method ${methodName} from logcat file ${logcat}"
       return
    fi

    
}



function ExpectedApplied_postproc()
{
    expectedCount=$1
    methodName=$2
    logcat_file=${logcat}_${methodName}_CCS


    ExtractMethodLogcat $methodName "constant_calculation_sinking: Try to optimize loop in method" "CCS"

    if [ ! -s ${logcat_file} ] ; then 
        str_res+="UNEXPECTED: Failed to extract Constant Calculation Sinking messages for method ${methodName}\n"
        res=$((res + 1))
        return
    fi

    successfully_sunk=`cat ${logcat_file} | grep "Constant has been sunk for the loop with head bb" | wc -l`

    if [[ "$successfully_sunk" == "$expectedCount" ]]; then
        str_res+="EXPECTED: Constant Calculation Sinking marker found $expectedCount time(s) for method $methodName;\n"
        res=$((res + 0))
    elif [[ "$successfully_sunk" != "$expectedCount" ]]; then
        str_res+="UNEXPECTED: Constant Calculation Sinking marker found $successfully_sunk time(s) instead of $expectedCount for method $methodName;\n"
        res=$((res + 1))
    else
        str_res+="UNEXPECTED: Postprocessing failed for method $methodName;\n"
        res=$((res + 1))
    fi

}

function ExpectedApplied_postproc_NTM()
{
    expectedCount=$1
    methodName=$2
    logcat_file=${logcat}_${methodName}_NTM

    ExtractMethodLogcat $methodName "non_temporal_move: Begin:" "NTM"

    successfully_mark=`cat ${logcat_file} | grep "Mark NonTemporal ArraySet" | wc -l`

    if [[ "$successfully_mark" == "$expectedCount" ]]; then
        str_res+="EXPECTED: Mark NonTemporal ArraySet marker found $expectedCount time(s) for method $methodName;\n"
        res=$((res + 0))
    elif [[ "$successfully_sunk" != "$expectedCount" ]]; then
        str_res+="UNEXPECTED: Mark NonTemporal ArraySet marker found $successfully_sunk time(s) instead of $expectedCount for method $methodName;\n"
        res=$((res + 1))
    else
        str_res+="UNEXPECTED: Postprocessing failed for method $methodName;\n"
        res=$((res + 1))
    fi

}




#Clean-up results dir before processing logcat:
rm -f ${logcat}_*

#Iterate over methods:
#CCS:
for i in "${testMethodsCounts[@]}" ; do
     methodName="${i%%:*}"
     expectedCount="${i##*:}"
     ExpectedApplied_postproc $expectedCount $methodName
done

#NTM:
for i in "${testMethodsCountsNTM[@]}" ; do
     methodName="${i%%:*}"
     expectedCount="${i##*:}"
     ExpectedApplied_postproc_NTM $expectedCount $methodName
done

## NonTemporalMove:
#expectedCountNonTeporalMove=10
#marked_by_nontemporalmove=`cat ${logcat} | grep "Mark NonTemporal ArraySet" | wc -l`
#if [[ "$marked_by_nontemporalmove" == "$expectedCountNonTeporalMove" ]]; then
#    str_res+="EXPECTED: Non temporal move optimization marker found $expectedCountNonTeporalMove time(s)\n"
#res=$((res + 0))
#    elif [[ "$marked_by_nontemporalmove" != "$expectedCountNonTeporalMove" ]]; then
#    str_res+="UNEXPECTED: Non temporal move optimization marker found $marked_by_nontemporalmove time(s) instead of $expectedCountNonTeporalMove\n"
#res=$((res + 1))
#    fi




Exit $((res)) "$str_res"

   


