#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


packagedir=`echo "$(cd $(dirname $0); pwd)/../"`


declare -a testMethodsCounts=(\
        "runTest:Environment of .* InvokeStaticOrDirect@.* no longer uses the value defined by .* IntConstant==2" \
        "runTest:Environment of .* InvokeStaticOrDirect@.* no longer uses the value defined by .* ParameterValue==24" \
        "runTest:Environment of .* InvokeStaticOrDirect@.* no longer uses the value defined by .* Phi==2" \
        "runTest:Environment of .* LoadClass@.* no longer uses the value defined by .* IntConstant==2" \
        "runTest:Environment of .* LoadClass@.* no longer uses the value defined by .* ParameterValue==6" \
        "runTest:Environment of .* NewInstance@.* no longer uses the value defined by .* IntConstant==3" \
        "runTest:Environment of .* NewInstance@.* no longer uses the value defined by .* ParameterValue==12" \
        "runTest:Environment of .* NewInstance@.* no longer uses the value defined by .* Phi==1" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* IntConstant==1" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* ParameterValue==7" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* Phi==1" \
        "runTest:Environment of .* SuspendCheck@.* no longer uses the value defined by .* ParameterValue==12" \
        "runTest:Environment of .* SuspendCheck@.* no longer uses the value defined by .* Phi==1" \
        "runTest:Environment of .* InvokeStaticOrDirect@.* still uses the value defined by .* NewInstance==4" \
        "runTest:Environment of .* InvokeStaticOrDirect@.* still uses the value defined by .* ParameterValue==4" \
        "runTest:Environment of .* LoadClass@.* still uses the value defined by .* ParameterValue==1" \
        "runTest:Environment of .* NewInstance@.* still uses the value defined by .* ParameterValue==2" \
        "runTest:Environment of .* SuspendCheck@.* still uses the value defined by .* ParameterValue==2" \
        "runTest:Removing .* Phi@.* because it is no longer used by any other instruction or environment.==2" \
        )
declare -a logcatLinesNumber=("runTest:91")
# include the package's postproc
if [ -f $packagedir/postproc_common ]; then
   source $packagedir/postproc_common
fi

