#!/bin/bash
#
# Copyright (C) 2008 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modified by Intel Corporation

msg() {
   [ "${VERBOSE}" = "on" ] && echo "$@" >> ${verbslog}
}

# the script accepts the following args:
expected=$1
output=$2

msg "diffexpected: expected=${expected}"
msg "diffexpected: output=${output}"

# diff -I "WARNING: linker" --strip-trailing-cr -u "$expected" "${test_results}/$output" # >/dev/null
diff -I "WARNING: linker" --strip-trailing-cr -u "$expected" "$output" # >/dev/null
diff -I "Loaded ART Extensions\|error: closed" --strip-trailing-cr -u "$expected" "$output"  >/dev/null
