#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

logcat=$1
str_res=""
res=0

function Exit()
{
    if [ $1 == 1 ]; then
        echo "FAILED: " $2
    else 
        echo "PASSED: inlining occured as expected"
    fi

    exit $1
}

function InvokeDirect()
{
    cat $logcat | grep "Successfully inlined .* OptimizationTests.${pckgname}.${testname}.Test.simple_method" > /dev/null
    if [ "$?" != "0" ]; then
        str_res+=" Test.simple_method inlining failed "
        echo `cat $logcat | grep "Test.simple_method"`
        res=1
    fi

    Exit $((res)) "$str_res"
}

function InvokeStatic()
{
    cat $logcat | grep "Successfully inlined .* OptimizationTests.${pckgname}.${testname}.Main.simple_method" > /dev/null
    if [ "$?" != "0" ]; then
        str_res+=" Main.simple_method inlining failed "
        echo `cat $logcat | grep "Main.simple_method"`
        res=1
    fi

    Exit $((res)) "$str_res"

}

function InvokeVirtual()
{
    cat $logcat | grep "Successfully inlined .* OptimizationTests.${pckgname}.${testname}.Test.simple_method" > /dev/null
    if [ "$?" != "0" ]; then
        str_res+=" Test.simple_method inlining failed "
        echo `cat $logcat | grep "Test.simple_method"`
        res=1
    fi

    Exit $((res)) "$str_res"

}

case $testname in
   InvokeDirect*) InvokeDirect
      ;;
   InvokeStatic*) InvokeStatic
      ;;
   InvokeVirtual*) InvokeVirtual
esac

