#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


ID=`date +%Y-%m-%d-%H-%M-%S-%N`
LOGCAT="$1"

function get_evaluated(){
#    local logcat=${1}
    cat "$LOGCAT" | grep "TrivialLoopEvaluator" | grep "has been statically evaluated" | awk -F"method " '{print $2}' | cut -d '"' -f 2
}

function search_method(){
    local method=${1}
    get_evaluated | grep "$method" 2>&1 >> /dev/null && return 0
    return 1
}
