#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


expected=$1
output=$2
testresdir=`dirname $output`

tr -ds '\r' '\n' < $expected > ${testresdir}/expected_n.txt 
cat $output | tr -ds '\r' '\n' | sed -e 's/Exception in thread "main" //' > ${testresdir}/output_filtered.txt

#diff  ${testresdir}/expected_n.txt ${testresdir}/output_filtered.txt
exec ${DIFFEXP} ${testresdir}/expected_n.txt ${testresdir}/output_filtered.txt

