#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

logcat=$1
str_res=""
res=0

function Exit()
{
    if [ $1 == 1 ]; then
        echo "FAILED: $2"
    else 
        echo "PASSED: $2"
    fi

    exit $1
}

function IsInlined()
{
## examples of successful inlining:
#
# I dex2oat : Successfully inlined int OptimizationTests.MInlining.InvokeDirect_DivZeroCheck_001.Test.b(int)
# I dex2oat : Successfully inlined float OptimizationTests.MInlining.InvokeDirect_Div_001.Test.b(int)
#
# I dex2oat : Successfully inlined int OptimizationTests.MInlining.InvokeStatic_DivZeroCheck_001.Main.b(int)
# I dex2oat : Successfully inlined float OptimizationTests.MInlining.InvokeStatic_Div_001.Main.b(int)
#
# I dex2oat : Successfully inlined int OptimizationTests.MInlining.InvokeVirtual_DivZeroCheck_001.Test.b(int)
# I dex2oat : Successfully inlined float OptimizationTests.MInlining.InvokeVirtual_Div_001.Test.b(int)
#
##
    cat $logcat | grep "Successfully inlined .* OptimizationTests.${pckgname}.${testname}.${fromclass}.b" > /dev/null
    if [ "$?" != "0" ]; then
        str_res+=" ${fromclass}.b inlining failed "
        echo `cat $logcat | grep "${fromclass}.b"`
        res=1
    fi
    str_res+=" Successfully inlined ${fromclass}.b;"

    Exit $((res)) "$str_res"
}

case $testname in
   InvokeDirect*)
      fromclass=Test
      ;;
   InvokeStatic*)
      fromclass=Main
      ;;
   InvokeVirtual*)
      fromclass=Test
      ;;
esac

IsInlined

