/*
 * Copyright (C) 2016 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OptimizationTests_AutoFastJNIDetection_PCRelativeAddressing_Main */

#ifndef _Included_OptimizationTests_AutoFastJNIDetection_PCRelativeAddressing_Main
#define _Included_OptimizationTests_AutoFastJNIDetection_PCRelativeAddressing_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OptimizationTests_AutoFastJNIDetection_PCRelativeAddressing_Main
 * Method:    nativeSetGlobal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_OptimizationTests_AutoFastJNIDetection_PCRelativeAddressing_Main_nativeSetGlobal
  (JNIEnv *, jobject, jint);

/*
 * Class:     OptimizationTests_AutoFastJNIDetection_PCRelativeAddressing_Main
 * Method:    nativeGetGlobal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_OptimizationTests_AutoFastJNIDetection_PCRelativeAddressing_Main_nativeGetGlobal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
