/*
 * Copyright (C) 2016 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OptimizationTests_AutoFastJNIDetection_Malloc_Main */

#ifndef _Included_OptimizationTests_AutoFastJNIDetection_Malloc_Main
#define _Included_OptimizationTests_AutoFastJNIDetection_Malloc_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OptimizationTests_AutoFastJNIDetection_Malloc_Main
 * Method:    nativeMalloc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_OptimizationTests_AutoFastJNIDetection_Malloc_Main_nativeMalloc
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
