#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


packagedir=`echo "$(cd $(dirname $0); pwd)/../"`

declare -a testMethodsCounts=(\
        "runTest:Environment of .* BoundsCheck@.* no longer uses the value defined by .* ArrayGet==1" \
        "runTest:Environment of .* BoundsCheck@.* no longer uses the value defined by .* Div==1" \
        "runTest:Environment of .* BoundsCheck@.* no longer uses the value defined by .* IntConstant==3" \
        "runTest:Environment of .* BoundsCheck@.* no longer uses the value defined by .* NewArray==1" \
        "runTest:Environment of .* BoundsCheck@.* no longer uses the value defined by .* ParameterValue==12" \
        "runTest:Environment of .* BoundsCheck@.* no longer uses the value defined by .* Phi==3" \
        "runTest:Environment of .* ClinitCheck@.* no longer uses the value defined by .* Add==1" \
        "runTest:Environment of .* ClinitCheck@.* no longer uses the value defined by .* IntConstant==2" \
        "runTest:Environment of .* ClinitCheck@.* no longer uses the value defined by .* ParameterValue==2" \
        "runTest:Environment of .* DivZeroCheck@.* no longer uses the value defined by .* ArrayGet==1" \
        "runTest:Environment of .* DivZeroCheck@.* no longer uses the value defined by .* IntConstant==2" \
        "runTest:Environment of .* DivZeroCheck@.* no longer uses the value defined by .* NewArray==1" \
        "runTest:Environment of .* DivZeroCheck@.* no longer uses the value defined by .* ParameterValue==6" \
        "runTest:Environment of .* DivZeroCheck@.* no longer uses the value defined by .* Phi==1" \
        "runTest:Environment of .* LoadClass@.* no longer uses the value defined by .* Add==1" \
        "runTest:Environment of .* LoadClass@.* no longer uses the value defined by .* IntConstant==2" \
        "runTest:Environment of .* LoadClass@.* no longer uses the value defined by .* ParameterValue==2" \
        "runTest:Environment of .* NewArray@.* no longer uses the value defined by .* Add==1" \
        "runTest:Environment of .* NewArray@.* no longer uses the value defined by .* ArrayGet==1" \
        "runTest:Environment of .* NewArray@.* no longer uses the value defined by .* IntConstant==5" \
        "runTest:Environment of .* NewArray@.* no longer uses the value defined by .* ParameterValue==6" \
        "runTest:Environment of .* NewArray@.* no longer uses the value defined by .* Select==1" \
        "runTest:Environment of .* NewInstance@.* no longer uses the value defined by .* Add==1" \
        "runTest:Environment of .* NewInstance@.* no longer uses the value defined by .* IntConstant==2" \
        "runTest:Environment of .* NewInstance@.* no longer uses the value defined by .* ParameterValue==2" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* Add==4" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* ArrayGet==1" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* Div==3" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* InstanceFieldGet==1" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* IntConstant==5" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* ParameterValue==24" \
        "runTest:Environment of .* NullCheck@.* no longer uses the value defined by .* Phi==5" \
        "runTest:Environment of .* SuspendCheck@.* no longer uses the value defined by .* Add==1" \
        "runTest:Environment of .* SuspendCheck@.* no longer uses the value defined by .* IntConstant==4" \
        "runTest:Environment of .* SuspendCheck@.* no longer uses the value defined by .* NewInstance==2" \
        "runTest:Environment of .* SuspendCheck@.* no longer uses the value defined by .* ParameterValue==8" \
        "runTest:Environment of .* SuspendCheck@.* no longer uses the value defined by .* Phi==2" \
        "runTest:Environment of .* SuspendCheck@.* no longer uses the value defined by .* Select==1" \
        "runTest:Environment of .* ClinitCheck@.* still uses the value defined by .* ParameterValue==4" \
        "runTest:Environment of .* ClinitCheck@.* still uses the value defined by .* Phi==1" \
        "runTest:Environment of .* LoadClass@.* still uses the value defined by .* ParameterValue==4" \
        "runTest:Environment of .* LoadClass@.* still uses the value defined by .* Phi==1" \
        "runTest:Environment of .* NewArray@.* still uses the value defined by .* NewInstance==2" \
        "runTest:Environment of .* NewArray@.* still uses the value defined by .* ParameterValue==7" \
        "runTest:Environment of .* NewArray@.* still uses the value defined by .* Phi==1" \
        "runTest:Environment of .* NewInstance@.* still uses the value defined by .* ParameterValue==4" \
        "runTest:Environment of .* NewInstance@.* still uses the value defined by .* Phi==1" \
        "runTest:Environment of .* SuspendCheck@.* still uses the value defined by .* ParameterValue==11" \
        "runTest:Environment of .* SuspendCheck@.* still uses the value defined by .* Phi==1" \
        "runTest:Removing .* Add@.* because it is no longer used by any other instruction or environment.==3" \
        "runTest:Removing .* ArrayGet@.* because it is no longer used by any other instruction or environment.==2" \
        "runTest:Removing .* IntConstant@.* because it is no longer used by any other instruction or environment.==1" \
        )
declare -a logcatLinesNumber=("runTest:167")


# include the package's postproc
if [ -f $packagedir/postproc_common ]; then
   source $packagedir/postproc_common
fi

