#!/bin/bash
#
# Copyright (C) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


echo "$1";
until [ -z "$1" ]
do
    if [ -z "$logcat" ]; then
	logcat=$1;
    elif [ -z "$bblocks" ]; then
	bblocks=$1;
    else
	otherins="$otherins$1";
    fi
  shift
done
#echo "1=$logcat";
#echo "2=$bblocks";
#echo "3=$otherins";

result="PASSED";
logstart=$(cat "${logcat}"| grep -n  "bb_simplifier: Start int"  | awk -F':' '{print $1}')
logend=$(cat "${logcat}"| grep -n  "bb_simplifier: End int"  | awk -F':' '{print $1}')

log=$(cat "${logcat}"| head -n +$logend | tail -n +$logstart | awk -F"bb_simplifier: " '{print $2}')

check1=$(echo "$log" | tail -1 | grep  "End int");
if [ "$check1" == "" ]; then
    result='FAILED';
    echo "check1 failed";
fi

check2=$(echo "$log" | grep  "Simplifying branching" | wc -l);
if [ "$check2" != "$bblocks" ]; then
    result='FAILED';
    echo "check2 failed";
fi


check3=$(echo "$log" | grep -E "Removed condition and [0-9]+ other instructions" | wc -l);
if [ "$check3" != "$bblocks" ]; then
    result='FAILED';
    echo "check3 failed";
fi

check4=$(echo "$log" | grep -E "Removed condition and [0-9]+ other instructions" |  grep -o '[0-9]\+' | tr -d '\n');

if [ "$check4" != "$otherins" ]; then
    result='FAILED';
    echo "check4 failed";
fi

if [ "$result" == "PASSED" ]; then
    echo "post-processing PASSED: Basic Blocks Simplifier successfully removed unused IF from the test method"
    exit 0
else
    echo "post-processing FAILED: Basic Blocks Simplifier failed to remove unused IF from the test method - unexpected"
    exit 1
fi

