#!/bin/bash
#
# Copyright (C) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

fail() { echo "FAIL: ${@}"; exit 1; }

JAVA_HOME=${JAVA_HOME:="<DEFAULT PATH TO JDK>"}
echo "JAVA_HOME $JAVA_HOME"
ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:="<DEFAULT PATH TO ANDROID SDK>"}
echo "ANDROID_SDK_ROOT $ANDROID_SDK_ROOT"
echo ANDROID_JAR=${ANDROID_JAR:=$ANDROID_SDK_ROOT/platforms/android-22/android.jar}
echo DX=${DX:=$ANDROID_SDK_ROOT/platform-tools/dx}

mkdir -p classes || fail "failed to create dir 'classes' "
rm -rf classes/*
$JAVA_HOME/bin/javac -d classes -cp ${ANDROID_JAR} src/*.java || fail "failed to compile StressRunner"
$DX --dex --debug --verbose --output=StressRunner.jar classes || fail "failed to create StressRunner.jar"
